name: zip plugin
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v1
     - name: action-zip
       # You may pin to the exact commit or the version.
       # uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
       uses: montudor/action-zip@v1.0.0
       with:
         # See montudor/action-zip README.md for more info
         args: zip -qq -r server_uploader.zip server_uploader
     - uses: actions/upload-artifact@v2
       with:
          name: server_uploader.zip
